### ISSUE TITLE
FunctionPrototype __new__

### ISSUE THREAD

**Issue by stewpend0us** [bjodah/sympy#8]
Why does FunctionPrototype __new__ return Token rather than Node? Better yet why does it need a __new__ method at all? I commented it out and all the ast tests still seem to pass?

**Comment by bjodah** [comment]
Oh, there's even some dead code in there. That's embarrassing: I probably missed it in some intermediate rewrite. I will look into it.

**Comment by bjodah** [comment]
You're right. That `__new__` does nothing useful (quite on the contrary) and should have been deleted. Feel free to delete it.

**Comment by bjodah** [comment]
@stewpend0us I went ahead and removed the constructor. Thank you for opening this issue.
